### ISSUE TITLE
client prefix not added to ipset members list

### ISSUE THREAD

**Issue by al-joshua** [wgnet/befw#10]
Hi folks,

I'm seeking for your support for the following.

I'm able to successfully register a service

`curl -X PUT localhost:8500/v1/agent/service/register -H "Content-Type: application/json" -d "{ \"Name\": \"rdp\", \"Port\": 3389, \"Tags\": [ \"befw\" ]}"`

so I can see it in Consul UI and I also have the corresponding ipset and Iptables rule created automatically

```
agorovoy@m1-net-hbfw01:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain BEFW (0 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             match-set rules_allow src
REJECT     all  --  anywhere             anywhere             match-set rules_deny src reject-with icmp-port-unreachable
ACCEPT     tcp  --  anywhere             anywhere             multiport dports 8300,8301,8302,8500,8501,8600
ACCEPT     tcp  --  anywhere             anywhere             multiport dports 3389 match-set rdp_tcp_3389 src
NFLOG      tcp  --  anywhere             anywhere             multiport dports 3389 nflog-group 402
REJECT     tcp  --  anywhere             anywhere             multiport dports 3389 reject-with icmp-port-unreachable
agorovoy@m1-net-hbfw01:~$ sudo ipset list
Name: rules_allow
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: rules_deny
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: rdp_tcp_3389
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:
```

Unfortunately I don't get how to add clients there, so that client prefixes populate the ipset. Doing something like this does not help
`consul kv put befw/$ipset$/rdp_tcp_3389/192.168.0.0/16 -1`
`curl -X PUT localhost:8500/v1/kv/befw/consul/rdp_tcp_3389/192.168.0.0/16 -H "Content-Type: application/json" -d "-1"`

What is the correct format of storing key/values in Consul KV store so that they be populated to local ipsets via befw automatically. Could you please provide an examples via both curl and cli.

Thanks,
Alex

**Comment by annmuor** [comment]
```
consul kv put befw/$service$/rdp_tcp_3389/192.168.0.0/16 -1
```
This may help.

**Comment by al-joshua** [comment]
Hi Ivan, thanks for your feedback

Unfortunately it didn't workout 

```
agorovoy@m1-net-hbfw01:~$ consul kv put befw/$service$/rdp_tcp_3389/192.168.0.0/16 -1
Success! Data written to: befw/$/rdp_tcp_3389/192.168.0.0/16
agorovoy@m1-net-hbfw01:~$ sudo ipset list
Name: rules_allow
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: rules_deny
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: rdp_tcp_3389
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:
agorovoy@m1-net-hbfw01:~$ 
```

**Comment by annmuor** [comment]
@al-joshua  have you specified right datacenter to use?

**Comment by al-joshua** [comment]
> @al-joshua have you specified right datacenter to use?

I guess so, otherwise it wouldn't have registered the "rdp" service and create the corresponding ipset "rdp_tcp_3389"

**Comment by annmuor** [comment]
Check it. You may use local DC for services and another DC for KV.

**Comment by al-joshua** [comment]
Ivan, as you can see the same dc is configured for both consul agent and befw service.

```
agorovoy@m1-net-hbfw01:~$ cat /etc/consul.d/consul.hcl | grep datacenter.=
datacenter = "m1"
agorovoy@m1-net-hbfw01:~$ cat /etc/befw.d/befw.conf | grep dc
dc=m1
agorovoy@m1-net-hbfw01:~$ 
```
Also, from the output below you can see that the services are in the catalog and the client keys are in the KV. The corresponding iptables and ipsets are created but the prefix is not in the ipset member list.

```
agorovoy@m1-net-hbfw01:~$ consul catalog datacenters
m1
agorovoy@m1-net-hbfw01:~$ consul catalog services
consul
http
rdp
agorovoy@m1-net-hbfw01:~$ consul kv get -detailed befw/$service$/m1/http_tcp_8080/192.168.0.0/16
CreateIndex      145
Flags            0
Key              befw/$/m1/http_tcp_8080/192.168.0.0/16
LockIndex        0
ModifyIndex      145
Session          -
Value            -1
agorovoy@m1-net-hbfw01:~$ consul kv get -detailed befw/$service$/m1/rdp_tcp_3389/192.168.0.0/16
CreateIndex      243
Flags            0
Key              befw/$/m1/rdp_tcp_3389/192.168.0.0/16
LockIndex        0
ModifyIndex      243
Session          -
Value
agorovoy@m1-net-hbfw01:~$ sudo ipset list
Name: rules_allow
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: rules_deny
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: rdp_tcp_3389
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: http_tcp_8080
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

```

While running befw-firewalld in debug mode I don't see it triggrs anything on putting the key into the KV store action.
How can I debug It furthermore?

Thanks

**Comment by annmuor** [comment]
It's obvious that "befw/$/m1/rdp_tcp_3389/192.168.0.0/16" is not equal to "
befw/$service$/m1/rdp_tcp_3389/192.168.0.0/16"
Probably you should configure your terminal the right way.

**Comment by al-joshua** [comment]
Hey Ivan, thanks for pointing it out! My terminal treats `$` as a special character so `/$service$` turns into `/$` and befw does not understand this key. 

Well, dealing with special characters helps `/\$service\$` :) or encode in url with `/%24service%24`

```
agorovoy@m1-net-hbfw01:~$ consul kv put befw/\$service\$/rdp_tcp_3389/192.168.0.0/16 -1
Success! Data written to: befw/$service$/rdp_tcp_3389/192.168.0.0/16
agorovoy@m1-net-hbfw01:~$ consul kv get -datacenter=m1 -recurse -detailed
CreateIndex      3102
Flags            0
Key              befw/$service$/rdp_tcp_3389/192.168.0.0/16
LockIndex        0
ModifyIndex      3102
Session          -
Value            -1
agorovoy@m1-net-hbfw01:~$ sudo ipset list
Name: rules_allow
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: rules_deny
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 1
Number of entries: 0
Members:

Name: rdp_tcp_3389
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 408
References: 1
Number of entries: 1
Members:
192.168.0.0/16
```

Now it works! thanks again!

Regards,
Alex

**Comment by al-joshua** [comment]
Let me please clarify one more thing. How does system differentiate the keys intended for a particular client node. Let's say I have `rdp_tcp_3389` service on multiple nodes but I want only a specific set of clients for one of them. Is it where the hierarchy in  key path comes in?

eg:

`befw/$service$/m1/m1-net-hbfw01/rdp_tcp_3389/` is applied only on `m1-net-hbfw01` host
`befw/$service$/m1/rdp_tcp_3389/` is applied to all nodes in m1 dc with the rdp service and so on?

The Consul agent stores everything and it is the local befw service that installs the keys significant for a host, right?

Documentation isn't clear on that. Could you please elaborate in that.

Thanks
