### ISSUE TITLE
errors during compilation

### ISSUE THREAD

**Issue by aokunev** [wgnet/befw#2]
Hi, not sure if the project is alive. I've got multiple errors while running make:
./build.sh
# _/home/xxx/befw/src/befw [_/home/xxx/befw/src/befw.test]
befw/struct.go:26:6: befwServiceProto redeclared in this block
	previous declaration at befw/config.go:37:6
befw/struct.go:28:6: RefreshMethod redeclared in this block
	previous declaration at befw/config.go:39:6
....

compilation worked fine after removing befw/struct.go. Looks like the file is a previous copy of config.go.

**Comment by annmuor** [comment]
Thanks, fixed
